### ISSUE TITLE
Not working in .Net standard 2.0 along with Windows Fall Creator Update (10.0; Build 16299)

### ISSUE THREAD

**Issue by nadkarninaveen** [Raamakrishnan/UWP-Styles-Library#2]
I checked the same solution on .Net standard 2.0 along with Windows Fall Creator Update (10.0; Build 16299), but its not working.

**Comment by Raamakrishnan** [comment]
This was developed long before .net standard came out and it is unmaintained since then. Its not surprising that there are problems with it. I am sorry but I can't help you with it.
